version: '3.1'

services:
  joomla:
    image: joomla:4.3.3-php8.1-apache
    restart: 'no'
    container_name: joomla
    links:
      - joomladb:mysql
    volumes:
      - ./mod_svtslider:/var/www/html/modules/mod_svtslider
      - ./a4joomla-lakeside3r-free:/var/www/html/templates/a4joomla-lakeside3r-free
    ports:
      - 8080:80
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: example

  joomladb:
    image: mysql:5.6
    container_name: joomladb
    restart: 'no'
    ports: 
      - 3306:3306
    volumes:
      - ./docker/mysql/dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: example